# Assingment "Assignment" System for DCT Academy's Code Platform

### Shreekar Hegde - User Id - 62

In [2]:
import numpy as np
import pandas as pd
import functools
from sqlalchemy import create_engine

In [3]:
engine = create_engine('postgresql+psycopg2://postgres:sudhanvasud@localhost/postgres')

print(engine.table_names())

['answers', 'ar_internal_metadata', 'assignment_groups', 'assignments', 'batch_students', 'batches', 'chat_rooms', 'code_play_backs', 'comments', 'courses', 'editor_settings', 'favourites', 'forks', 'friendly_id_slugs', 'list_assignments', 'lists', 'messages', 'notification_types', 'notifications', 'permissions', 'practice_students', 'practices', 'questions', 'read_questions', 'roles', 'schema_migrations', 'sections', 'solutions', 'student_courses', 'student_logs', 'students', 'submission_timers', 'submissions', 'taggings', 'tags', 'test_cases', 'users', 'videos']

## Creating list of dataframe of all tables, a dictionary mapping to corresponding dataframe

In [4]:
# Dictionary of all the tables and their columns
table_columns = {}

# Dictionary of all dataframes mapped with table names
df_all = {}

# List of all dataframes of all tables
df_list = []

for table in engine.table_names():
    df = pd.read_sql(table, engine)
    df_all[table] = df
    df_list.append(df)
    table_columns[table] = list(df.columns)

In [31]:
shreekar_submissions = df_all['submissions'][df_all['submissions']['user_id'] == 62] \
    .merge(df_all['assignments'], left_on='assignment_id', right_on='id')
shreekar_submissions.drop(['statement', 'output', 'user_id_x', 'language', 'assignment_id',
       'practice_id', 'created_at_x', 'updated_at_x', 'is_checked',
       'time_in_seconds', 'pass', 'fail', 'total', 'points_x', 'id_y', 'title',
       'body', 'url', 'created_at_y', 'updated_at_y', 'user_id_y', 'source',
       'is_allowed', 'code', 'approved', 'points_y', 'minutes',
       'function_name', 'input_size'], axis=1, inplace=True)
shreekar_submissions.to_html('shreekar.html')
shreekar_submissions

,statement,language,created_at_x,updated_at_x,id_y,body,url,created_at_y,updated_at_y
0,function findNotBookedTables(a){\n\tif(a.lengt...,javascript,2018-07-09 16:23:28.757343,2018-07-09 16:23:28.757343,26,"<p>In this challenge, we&#39;ll use an array t...",,2018-01-11 10:04:29.976612,2018-06-13 15:29:36.726507
1,\n\n\nfunction findNotBookedTables(array){\n\t...,javascript,2018-07-25 16:48:36.106752,2018-07-25 16:48:36.106752,26,"<p>In this challenge, we&#39;ll use an array t...",,2018-01-11 10:04:29.976612,2018-06-13 15:29:36.726507
2,function countUpThenDown(a){\n\tresult = [];\n...,javascript,2018-07-10 06:32:23.403438,2018-07-10 06:32:23.403438,34,<p>Create a function that takes a number as an...,,2018-01-11 10:10:42.141483,2018-06-18 06:20:33.785921
3,"function sayAgain(a,b){\n\tvar result = \t'';\...",javascript,2018-07-10 09:42:44.668082,2018-07-10 09:42:44.668082,23,<p>Create a function&nbsp;<code>sayAgain</code...,,2018-01-11 10:01:50.124490,2018-06-14 14:38:24.709119
4,"function authenticate(a,b){\n\tvar result;\n\t...",javascript,2018-07-10 17:22:24.736566,2018-07-10 17:22:24.736566,33,"<p>Create a function,&nbsp;<code>authenticate<...",,2018-01-11 10:10:13.775287,2018-06-25 09:26:12.637900
5,function evenOdd(a){\n\tif(a.length == 0){\n\t...,javascript,2018-07-11 14:04:56.669331,2018-07-11 14:04:56.669331,44,<p>Write a function that accepts and array of ...,,2018-01-11 10:23:46.883915,2018-06-13 09:10:26.561923
6,"function iPush(a,b){\n\tvar i;\n\tfor(i = 0; i...",javascript,2018-07-11 15:57:47.617305,2018-07-11 15:57:47.617305,48,<p>Write the function (iPush) which is a repli...,,2018-01-11 10:26:55.001849,2018-06-14 06:47:52.256744
7,function vowelCount(a){\n\tif(a.length === 0){...,javascript,2018-07-10 11:27:19.504793,2018-07-10 11:27:19.504793,24,<p>Create the function&nbsp;<code>vowelCount(s...,,2018-01-11 10:02:31.564450,2018-06-13 15:26:36.773684
8,function converter(a){\n\tvar store;\n\tvar ce...,javascript,2018-07-11 13:23:07.950043,2018-07-11 13:23:07.950043,14,<p>Write a converter function that accepts a t...,,2018-01-11 04:31:40.426231,2018-06-18 06:23:03.373432
9,"function maxOfThree(a,b,c){\n\tif((a >= b) && ...",javascript,2018-07-11 15:22:15.803020,2018-07-11 15:22:15.803020,17,<p>Create the function&nbsp;<code>maxOfThree</...,,2018-01-11 09:57:50.551634,2018-06-18 09:08:06.391585
10,function findEO(a){\nif(a % 2 == 0){\n retur...,javascript,2018-07-14 08:29:48.943632,2018-07-14 08:29:48.943632,344,<p>Create a function that takes an integer as ...,,2018-07-01 05:10:03.381271,2018-07-01 05:10:03.381271
11,function abbreviate(a){\n\tvar result = [];\n\...,javascript,2018-07-14 08:22:31.276283,2018-07-14 08:22:31.276283,341,<p>Write a function to convert a name into ini...,,2018-07-01 04:50:38.090675,2018-07-01 04:50:38.090675
12,function summation(a){\n\tvar sum = 0;\n\tfor(...,javascript,2018-07-14 08:40:04.626806,2018-07-14 08:40:04.626806,346,<h1>Summation</h1>\r\n\r\n<p>Write a program t...,,2018-07-01 05:16:29.303211,2018-07-01 05:16:35.396415
13,function squareSum(a){\n\tvar sum = 0;\n\tfor(...,javascript,2018-07-14 09:04:27.832152,2018-07-14 09:04:27.832152,351,<p>Complete the&nbsp;<code>squareSum</code>/<c...,,2018-07-14 02:59:28.114936,2018-07-14 02:59:28.114936
14,function binaryToNumber(a){\n\tvar sum = 0;\n\...,javascript,2018-07-14 09:18:46.441558,2018-07-14 09:18:46.441558,352,<p>Given an array of one&#39;s and zero&#39;s ...,,2018-07-14 04:02:23.537830,2018-07-14 04:02:23.537830
15,"function isUpperCaseAt(a,b){\n\tif(a.charAt(b)...",javascript,2018-07-21 13:50:20.807910,2018-07-21 13:50:20.807910,128,<p>Write a JavaScript function to test whether...,,2018-01-26 11:56:19.035417,2018-06-07 11:21:06.125936
16,"function stringChop(a,b){\n\tvar c= [];\n\tif(...",javascript,2018-07-21 15:38:05.511149,2018-07-21 15:38:05.511149,89,<p>Write a JavaScript function to chop a strin...,,2018-01-26 11:19:05.135903,2018-06-07 11:05:44.991307
17,"function startsWith(a,b){\n\tvar x = a.split('...",javascript,2018-07-21 13:58:24.811484,2018-07-21 13:58:24.811484,134,<p>Write a JavaScript function to test whether...,,2018-01-26 11:59:44.035842,2018-06-07 11:24:48.672805
18,"function findWord(a,b){\n\tvar count = 0;\n\ta...",javascript,2018-07-21 16:15:08.927907,2018-07-21 16:15:08.927907,102,<p>Write a JavaScript function to find a word ...,,2018-01-26 11:37:07.028945,2018-06-07 11:10:17.358219
19,function unCap(a){\n\tvar res = '';\n\ta = a.s...,javascript,2018-07-21 19:18:43.087858,2018-07-21 19:18:43.087858,122,<p>Write a JavaScript function to Uncapitalize...,,2018-01-26 11:52:13.384933,2018-06-07 11:13:09.429015
20,"function joinArray(array,symbol){\n\tvar newAr...",javascript,2018-07-25 04:24:33.996030,2018-07-25 04:24:33.996030,80,<p>Write a simple JavaScript Function to join ...,,2018-01-26 11:04:28.073953,2018-06-13 07:30:43.201521
21,\tfunction printArray(array){\t\n\t\tvar resul...,javascript,2018-07-24 17:00:32.094884,2018-07-24 17:00:32.094884,106,<p>Write a JavaScript program which prints the...,,2018-01-26 11:39:40.932360,2018-07-23 09:40:57.646528
22,function putDash(number){\n\tvar result = [];\...,javascript,2018-07-24 12:47:53.135481,2018-07-24 12:47:53.135481,83,<p>Write a JavaScript function which accept a ...,,2018-01-26 11:05:56.678813,2018-07-23 17:09:27.754881
23,function isArray(value){\n\tif(Array.isArray(v...,javascript,2018-07-24 12:55:52.694316,2018-07-24 12:55:52.694316,73,<p>Write a JavaScript function to check whethe...,,2018-01-26 10:59:57.349713,2018-06-10 01:58:42.570651
24,var sum1;\nvar store = [];\nvar alphabets = 'a...,javascript,2018-07-24 17:32:26.711820,2018-07-24 17:32:26.711820,63,<p>You are given two strings S1 and S2. You ne...,,2018-01-16 11:25:09.500578,2018-06-09 12:06:45.729359
25,"function removeArrayElements(arr,ele){\n\tvar ...",javascript,2018-07-24 17:24:48.114813,2018-07-24 17:24:48.114813,141,<p>Write a JavaScript function to remove a spe...,,2018-01-26 12:08:29.338657,2018-06-09 11:16:42.315209
26,function randomElement(array){\n\tif(array.len...,javascript,2018-07-25 03:27:46.112373,2018-07-25 03:27:46.112373,144,<p><strong>&nbsp;</strong>Write a JavaScript f...,,2018-01-26 12:15:29.698296,2018-06-13 07:36:41.524393
27,\n\tfunction zooInventory(array){\n\t\tvar res...,javascript,2018-07-26 08:57:16.987320,2018-07-26 08:57:16.987320,30,<p>Write a function&nbsp;<code>zooInventory</c...,,2018-01-11 10:07:37.911678,2018-07-23 08:43:43.424881
28,function findUnique(array){\n\tif(array.length...,javascript,2018-07-25 17:26:49.089250,2018-08-02 13:22:24.467730,353,<p>Write a function called&nbsp;<code>findUniq...,,2018-07-14 04:06:20.351763,2018-07-14 04:06:20.351763
29,"function sumTwoArrayIndexes(array1,array2){\n\...",javascript,2018-07-28 17:30:24.034837,2018-07-28 17:30:24.034837,121,<p>There are two arrays with individual values...,,2018-01-26 11:51:19.046207,2018-06-12 16:01:26.763645
30,"function pairElement(array,target){\n\tif(arra...",javascript,2018-07-28 18:40:55.348293,2018-07-28 18:40:55.348293,136,<p>Write a JavaScript program to find a pair o...,,2018-01-26 12:02:33.457757,2018-06-10 08:10:45.877990
31,"function superPower(superHeroes,name){\n\tif(n...",javascript,2018-07-29 13:22:54.194104,2018-07-29 13:22:54.194104,331,<p>Write a function to display the powers of t...,,2018-06-18 08:13:20.408245,2018-06-18 15:35:33.934510
32,function findDuplicate(array){\n\tif(array.len...,javascript,2018-07-29 10:03:18.649884,2018-07-29 10:03:18.649884,123,<p>Write a&nbsp;program to find duplicate valu...,,2018-01-26 11:52:39.966203,2018-06-09 12:07:58.789556
33,function frequency(string){\n\tvar obj = {};\n...,javascript,2018-07-29 12:06:46.350129,2018-07-29 12:06:46.350129,62,<p>Write a function that takes a&nbsp;<strong>...,,2018-01-11 10:36:52.906410,2018-06-14 14:46:49.205537
34,"function rotateStr(str){\n\tvar newArray = [],...",javascript,2018-07-29 12:40:15.234374,2018-07-29 12:40:15.234374,357,<p>Create a function that accepts a string arg...,,2018-07-27 17:22:29.823053,2018-07-27 17:22:29.823053
35,function readingStatus(library){\n\t\t\t\tres ...,javascript,2018-07-31 12:32:56.063280,2018-07-31 12:32:56.063280,174,<p>Write a JavaScript program to display the r...,,2018-02-01 04:53:56.084118,2018-06-18 09:15:25.701072